### ISSUE TITLE
No such file Problem

### ISSUE THREAD

**Issue by HiNeal** [jopemachine/alfred-chromium-workflow#11]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/64223900/191883051-018b4230-25b3-4957-9b66-0f649b6630c1.png">

Hello I installed this and it show the above screenshot

**Comment by jopemachine** [comment]
It could happen when you have no bookmark history file inside of your profile folder.
By any chance, did you try this workflow right after installing the browser?
If so, please try this workflow again after launching the installed browser.
If not, you can try to change your profile, browser.
If you can not resolve the problem, I appreciate it if you could share alfred debugger logs

**Comment by HiNeal** [comment]
Hey. this is the debugger logs, and i did install browser chrome, the chrome path is below, but even i install chrome, i dont have the path /Users/oyca168/Library/Application Support/Google/Chrome/Default/History
[log.txt](https://github.com/jopemachine/alfred-chromium-workflow/files/9630933/log.txt)
<img width="478" alt="image" src="https://user-images.githubusercontent.com/64223900/191898018-a9a78958-89c0-4a3e-a7a3-18322efff0ac.png">

**Comment by jopemachine** [comment]
Thanks for letting me know.
You can change your selected profile by `ch profile`.
This should work after changing profile to `Profile 3` through `ch profile`

**Comment by HiNeal** [comment]
Nice ! It did works, thanks
