### ISSUE TITLE
`ch profile` cannot find user data directory

### ISSUE THREAD

**Issue by dropshoty** [jopemachine/alfred-chromium-workflow#2]
I'm getting this error when running any of the commands, any idea on how to troubleshoot?
![Screen Shot 2022-05-30 at 8 11 24 AM](https://user-images.githubusercontent.com/38113114/170989890-e28229c5-55a7-4661-99b9-388f9ccf4779.JPG)

**Comment by jopemachine** [comment]
I guess this is likely related to your browser config.

Is Chrome installed on your mac?

If not and you didn't change your browser config yet, that bug could show up.

(I think I need to mention about this in the installation section.)

You can try to change the browser config through `ch browser`.

If after changing the browser config, the bug still happens, could you show me the [Alfred debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/)?

This can help me debug what happened more easily.

**Comment by dropshoty** [comment]
I do have Chrome installed, with two profiles.  It looks like I don't have a default directory, and the profiles are 7 and 8.  

Do I need to change one of the profiles to Default?

![Screen Shot 2022-05-30 at 9 18 26 AM](https://user-images.githubusercontent.com/38113114/171000605-eb15dead-4561-430a-9f80-c5b3cfa44311.JPG)

**Comment by jopemachine** [comment]
Thanks for sharing this.

> Do I need to change one of the profiles to Default?

No, this is a bug that should be fixed.

This bug should be fixed in the 0.1.5

Could you retry the `ch browser` in the 0.1.5 version?

**Comment by dropshoty** [comment]
The update seems to have fixed my issue, ch browser shows Chrome with a check.  Thank you!
