### ISSUE TITLE
(bug) Case sensitive in tab search

### ISSUE THREAD

**Issue by joelmellon** [jopemachine/alfred-chromium-workflow#8]
I've been using another workflow to search through Chrome and Safari tabs for quite a few years now and I've always hated how slow it was. This workflow is 10x faster which is insanely great!

Unfortunately, it's nearly useless to me without being case-insensitive.

It does seem to work sometimes, so I'm not sure if it's a bug or just partially case-insensitive or what, eg. maybe the URL is case insensitive but the tab title isn't? Regardless, I've found quite a few cases where it doesn't work case-insensitively, primarily YouTube which doesn't use stubs or otherwise have anything useful to search in their URLs, so search terms generally only match tab titles.

To reproduce:
1. Go to https://www.youtube.com/watch?v=0EqSXDwTq6U
2. Activate Alfred
3. Type "cht Charlie"
4. Notice "Charlie bit my finger! ORIGINAL..." appears as a result.
5. Backspace to change Alfred text to "cht charlie" - with lowercase c in charlie
6. Notice no results appear.

If this isn't 100% reproducible let me know and I'll provide system info, etc.

Thanks!

**Comment by jopemachine** [comment]
Thanks for your detailed report!

This bug is fixed now (on 0.2.8)

**Comment by joelmellon** [comment]
Thanks so much for the quick reply and fix!

I do have a thought [here](https://github.com/jopemachine/alfred-chromium-workflow/commit/9f1d001766d01179b8975006cf975a95ce6e2161#r84417648). It's a small bug most likely, but I can't test it since `0.2.8` seems to have broken `./alfred-chromium-workflow` on my machine. I created a new issue for that: #9 

Sorry for all the trouble!
