### ISSUE TITLE
Code 126: /bin/bash: ./alfred-chromium-workflow: Bad CPU type in executable

### ISSUE THREAD

**Issue by joelmellon** [jopemachine/alfred-chromium-workflow#9]
I just upgraded from `0.2.7` to `0.2.8` and got this error:

<img width="977" alt="Screen Shot 2022-09-19 at 11 45 15 AM" src="https://user-images.githubusercontent.com/13803216/191096036-a7bad6b4-2d73-4040-829d-ea339e4cd500.png">

I deleted and reinstalled `0.2.7` to confirm something changed, and the error goes away, and `cht` works perfectly.

Steps to reproduce:
1. Download [alfred-chromium-workflow.alfredworkflow 0.2.8](https://github.com/jopemachine/alfred-chromium-workflow/releases/download/0.2.8/alfred-chromium-workflow.alfredworkflow)
2. Open debugger in workflow.
3. In Alfred: `cht anything`
4. Notice "Code 126: /bin/bash: ./alfred-chromium-workflow: Bad CPU type in executable" error in debug console.

Workaround: revert to `0.2.7`.

My system:
macOS Monterey 12.3.1 (21E258) on Intel chip.
Alfred 4.7 [1306] then upgraded to Alfred 5.0.2 [2073] and experienced the same issue.

It doesn't look like much changed in `0.2.8` executable-wise, but maybe the [magefile version changes](https://github.com/jopemachine/alfred-chromium-workflow/compare/0.2.7...0.2.8) had some effect? ‾\_(ツ)_/‾

**Comment by jopemachine** [comment]
I think this would be resolved on 0.2.9, but I can't test it because I don't have intel mac now..

Would you mind testing if it works on intel mac if you are okay?

**Comment by joelmellon** [comment]
It works. Thanks again. 🙏

**Comment by Asxing** [comment]
This issue is still present in the latest 0.3.0, the rollback using 0.2.9 is normal.
